### ISSUE TITLE
STL too small

### ISSUE THREAD

**Issue by fatpanda303** [hrobeers/finFoil#56]
Hi,
I love your program (v1.1.1.486) , but when I try to create an STL file, the fin is tiny.  Using the default settings creates the attached fin.  When I view this in sketchup or Autodesk 123D the product is super small.  I double checked the file using http://www.viewstl.com/ and it shows that it is super small too.

Is there an error with the STL output?
Tim

**Comment by hrobeers** [comment]
Nope, the STL in exported in meters, the SI unit for length.
Using tools like OpenSCAD, you can easily scale it by a factor 1000 to get millimeters.

Glad you like finFoil, unfortunately development has stalled a bit due to a lack of donations and too many businesses contacting me for free help.
